// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgtnfwlZffU077O6bdKpRwbHU5rHeNvxQ',
    appId: '1:153451851470:web:f00deb7a450c4785ea6a9f',
    messagingSenderId: '153451851470',
    projectId: 'reddit-clone-96e88',
    authDomain: 'reddit-clone-96e88.firebaseapp.com',
    storageBucket: 'reddit-clone-96e88.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAGKsq_oUz0lDFDb7NZmX8FqNlCFk7Py4',
    appId: '1:153451851470:android:d4a2080c7360d0baea6a9f',
    messagingSenderId: '153451851470',
    projectId: 'reddit-clone-96e88',
    storageBucket: 'reddit-clone-96e88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDavCPaDzSgnDlTxos6g8M4Oimy35k6s54',
    appId: '1:153451851470:ios:9cff331f13df6400ea6a9f',
    messagingSenderId: '153451851470',
    projectId: 'reddit-clone-96e88',
    storageBucket: 'reddit-clone-96e88.appspot.com',
    iosClientId: '153451851470-8fk2skbh4q1058605l090ij3d95s72ul.apps.googleusercontent.com',
    iosBundleId: 'com.thejitenpatel.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDavCPaDzSgnDlTxos6g8M4Oimy35k6s54',
    appId: '1:153451851470:ios:9cff331f13df6400ea6a9f',
    messagingSenderId: '153451851470',
    projectId: 'reddit-clone-96e88',
    storageBucket: 'reddit-clone-96e88.appspot.com',
    iosClientId: '153451851470-8fk2skbh4q1058605l090ij3d95s72ul.apps.googleusercontent.com',
    iosBundleId: 'com.thejitenpatel.redditClone',
  );
}
